tickers: ["AAPL", "MSFT", "NVDA", "AMZN", "GOOGL", "META", "TSLA", "JPM", "AVGO", "COST"]
history_buffer: 12
months_to_test: 2

ui:
  green_style: "ðŸŸ¢" # You can also use "PASS" or "GREEN"
  red_style: "ðŸ”´"   # You can also use "FAIL" or "RED"